In [1]:
# Librerias
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.metrics import classification_report


In [2]:
url='https://raw.githubusercontent.com/chrisrueda/EndomorfismoII_2024/main/PROYECTOS/SEGUNDO%20PARCIAL/mora_cdto.csv'

df=pd.read_csv(url)

df.head(10)

ID     CU  G  ED       EC   E  M1  M2  M3  M4  ...       D4       D5  \
0   1   2000  F   2   Casado  24   2   2  -1  -1  ...      0.0      0.0   
1   2  12000  F   2  Soltero  26  -1   2   0   0  ...    327.2    345.5   
2   3   9000  F   2  Soltero  34   0   0   0   0  ...   1433.1   1494.8   
3   4   5000  F   2   Casado  37   0   0   0   0  ...   2831.4   2895.9   
4   5   5000  M   2   Casado  57  -1   0  -1   0  ...   2094.0   1914.6   
5   6   5000  M   1  Soltero  37   0   0   0   0  ...   1939.4   1961.9   
6   7  50000  M   1  Soltero  29   0   0   0   0  ...  54265.3  48300.3   
7   8  10000  F   2  Soltero  23   0  -1  -1   0  ...     22.1    -15.9   
8   9  14000  F   3   Casado  28   0   0   2   0  ...   1221.1   1179.3   
9  10   2000  M   3  Soltero  35  -2  -2  -2  -2  ...      0.0   1300.7   

        D6      P1      P2      P3      P4      P5      P6  SP  
0      0.0     0.0    68.9     0.0     0.0     0.0     0.0  Si  
1    326.1     0.0   100.0   100.0   100.0     0.0   200.0  Si  
2   1554.9   151.8   150.0   100.0   100.0   100.0   500.0  No  
3   2954.7   200.0   201.9   120.0   110.0   106.9   100.0  No  
4   1913.1   200.0  3668.1  1000.0   900.0    68.9    67.9  No  
5   2002.4   250.0   181.5    65.7   100.0   100.0    80.0  No  
6  47394.4  5500.0  4000.0  3800.0  2023.9  1375.0  1377.0  No  
7     56.7    38.0    60.1     0.0    58.1   168.7   154.2  No  
8    371.9   332.9     0.0    43.2   100.0   100.0   100.0  No  
9   1391.2     0.0     0.0     0.0  1300.7   112.2     0.0  No  

[10 rows x 25 columns]

# Tratamiento de los datos

### Analisis estadistico

In [3]:
df.count()


ID    30000
CU    30000
G     29997
ED    30000
EC    29999
E     30000
M1    30000
M2    30000
M3    30000
M4    30000
M5    30000
M6    30000
D1    30000
D2    30000
D3    30000
D4    30000
D5    30000
D6    30000
P1    30000
P2    30000
P3    30000
P4    30000
P5    30000
P6    30000
SP    30000
dtype: int64

In [4]:
df.dtypes

ID      int64
CU      int64
G      object
ED      int64
EC     object
E       int64
M1      int64
M2      int64
M3      int64
M4      int64
M5      int64
M6      int64
D1    float64
D2    float64
D3    float64
D4    float64
D5    float64
D6    float64
P1    float64
P2    float64
P3    float64
P4    float64
P5    float64
P6    float64
SP     object
dtype: object

In [5]:
df.describe()

ID             CU            ED             E            M1  \
count  30000.000000   30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   16748.432267      1.853133     35.485500     -0.016700   
std     8660.398374   12974.766157      0.790349      9.217904      1.123802   
min        1.000000    1000.000000      0.000000     21.000000     -2.000000   
25%     7500.750000    5000.000000      1.000000     28.000000     -1.000000   
50%    15000.500000   14000.000000      2.000000     34.000000      0.000000   
75%    22500.250000   24000.000000      2.000000     41.000000      0.000000   
max    30000.000000  100000.000000      6.000000     79.000000      8.000000   

                 M2            M3            M4            M5            M6  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      -0.133767     -0.166200     -0.220667     -0.266200     -0.291100   
std        1.197186      1.196868      1.169139      1.133187      1.149988   
min       -2.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        8.000000      8.000000      8.000000      8.000000      8.000000   

       ...             D3            D4            D5            D6  \
count  ...   30000.000000  30000.000000  30000.000000  30000.000000   
mean   ...    4701.315480   4326.294897   4031.140097   3887.176040   
std    ...    6934.938743   6433.285613   6079.715577   5955.410754   
min    ...  -15726.400000 -17000.000000  -8133.400000 -33960.300000   
25%    ...     266.625000    232.675000    176.300000    125.600000   
50%    ...    2008.850000   1905.200000   1810.450000   1707.100000   
75%    ...    6016.475000   5450.600000   5019.050000   4919.825000   
max    ...  166408.900000  89158.600000  92717.100000  96166.400000   

                 P1            P2            P3            P4            P5  \
count  30000.000000   30000.00000  30000.000000  30000.000000  30000.000000   
mean     566.358050     592.11635    522.568150    482.607687    479.938763   
std     1656.328035    2304.08704   1760.696147   1566.615974   1527.830568   
min        0.000000       0.00000      0.000000      0.000000      0.000000   
25%      100.000000      83.30000     39.000000     29.600000     25.250000   
50%      210.000000     200.90000    180.000000    150.000000    150.000000   
75%      500.600000     500.00000    450.500000    401.325000    403.150000   
max    87355.200000  168425.90000  89604.000000  62100.000000  42652.900000   

                 P6  
count  30000.000000  
mean     521.550257  
std     1777.746578  
min        0.000000  
25%       11.775000  
50%      150.000000  
75%      400.000000  
max    52866.600000  

[8 rows x 22 columns]

### Comprobar los valores de las clases

In [6]:
print("VALORES DISCRETOS")
val_CU = df["CU"].unique()
print(val_CU)

VALORES DISCRETOS
[  2000  12000   9000   5000  50000  10000  14000  20000  26000  63000
   7000  25000  32000  36000  18000  13000  45000   6000  23000  16000
  28000   1000   4000  21000  15000  38000  31000  40000   8000  29000
  34000  30000   3000  24000  47000  48000  35000  33000  11000  42000
  17000  37000  27000  22000  19000  51000  46000  44000  41000  49000
  39000  58000  60000  62000  61000  70000  67000  68000  43000  55000
  54000 100000  53000  71000  56000  52000  75000  64000   1600  57000
  59000  66000  72000  32768  74000  80000  76000  69000  65000  78000
  73000]


In [7]:
#Comprobar los valores de Genero
print("VALORES DISCRETOS")
val_G = df["G"].unique()
print(val_G)

VALORES DISCRETOS
['F' 'M' 'O' nan]


In [8]:
#Comprobar los valores de Estado Civil
print("VALORES DISCRETOS")
val_EC = df["EC"].unique()
print(val_EC)

VALORES DISCRETOS
['Casado' 'Soltero' 'Otros' nan '0']


In [9]:
#Comprobar los valores de instruccion educativa
print("VALORES DISCRETOS")
val_ED = df["ED"].unique()
print(val_ED)

VALORES DISCRETOS
[2 1 3 5 4 6 0]


In [10]:
val_M1 = df['M1'].unique()
print(val_M1)

[ 2 -1  0 -2  1  3  4  8  7  5  6]


In [11]:
val_M2 = df["M2"].unique()
print(val_M2)

[ 2  0 -1 -2  3  5  7  4  1  6  8]


In [12]:
val_M3 = df["M3"].unique()
print(val_M3)

[-1  0  2 -2  3  4  6  7  1  5  8]


In [13]:
val_M4 = df["M4"].unique()
print(val_M4)

[-1  0 -2  2  3  4  5  7  6  1  8]


In [14]:
val_M5 = df["M5"].unique()
print(val_M5)

[-2  0 -1  2  3  5  4  7  8  6]


In [15]:
val_M6 = df["M6"].unique()
print(val_M6)

[-2  2  0 -1  3  6  4  7  8  5]


In [16]:
df['SP'].unique()

array(['Si', 'No'], dtype=object)

### Imputacion

In [17]:
# Remplazar nan
#Categorico
mas_freq = df["G"].value_counts().idxmax()
print(f"La variable mas frecuente para Class es {mas_freq}")
#imputar la variable
df["G"].replace(np.nan,mas_freq,inplace=True)
#Comprobar faltantes
df["G"].unique()

La variable mas frecuente para Class es F


C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\2095266933.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["G"].replace(np.nan,mas_freq,inplace=True)


array(['F', 'M', 'O'], dtype=object)

In [18]:
#Categorico
mas_freqEC = df["EC"].value_counts().idxmax()
print(f"La variable mas frecuente para Class es {mas_freqEC}")
#imputar la variable
df["EC"].replace(np.nan,mas_freqEC,inplace=True)
df['EC'].replace('0',mas_freqEC,inplace=True)
#Comprobar faltantes
df["EC"].unique()

La variable mas frecuente para Class es Soltero


C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\4132263309.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["EC"].replace(np.nan,mas_freqEC,inplace=True)
C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\4132263309.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exa

array(['Casado', 'Soltero', 'Otros'], dtype=object)

In [19]:
#Categorico
mas_freqED = df["ED"].value_counts().idxmax()
print(f"La variable mas frecuente para ED es {mas_freqED}")
#imputar la variable
df["ED"].replace(0,mas_freqED,inplace=True)
df["ED"].replace(5,mas_freqED,inplace=True)
df["ED"].replace(6,mas_freqED,inplace=True)

#Comprobar faltantes
df["ED"].unique()

La variable mas frecuente para ED es 2


C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\3053715643.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["ED"].replace(0,mas_freqED,inplace=True)
C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\3053715643.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example,

array([2, 1, 3, 4], dtype=int64)

In [20]:
# Valores no permitidos en M1-M6 son 0 y -2
df['M1'].replace(0,np.nan,inplace=True)
df['M1'].replace(-2,np.nan,inplace=True)
df['M2'].replace(0,np.nan,inplace=True)
df['M2'].replace(-2,np.nan,inplace=True)
df['M3'].replace(0,np.nan,inplace=True)
df['M3'].replace(-2,np.nan,inplace=True)
df['M4'].replace(0,np.nan,inplace=True)
df['M4'].replace(-2,np.nan,inplace=True)
df['M5'].replace(0,np.nan,inplace=True)
df['M5'].replace(-2,np.nan,inplace=True)
df['M6'].replace(0,np.nan,inplace=True)
df['M6'].replace(-2,np.nan,inplace=True)
mas_freqM1 = df["M1"].value_counts().idxmax()
mas_freqM2 = df["M2"].value_counts().idxmax()
mas_freqM3 = df["M3"].value_counts().idxmax()
mas_freqM4 = df["M4"].value_counts().idxmax()
mas_freqM5 = df["M5"].value_counts().idxmax()
mas_freqM6 = df["M6"].value_counts().idxmax()
print(f"La variable mas frecuente para M1 es {mas_freqM1}")
print(f"La variable mas frecuente para M2 es {mas_freqM2}")
print(f"La variable mas frecuente para M3 es {mas_freqM3}")
print(f"La variable mas frecuente para M4 es {mas_freqM4}")
print(f"La variable mas frecuente para M5 es {mas_freqM5}")
print(f"La variable mas frecuente para M6 es {mas_freqM6}")


df['M1'].replace(np.nan,mas_freqM1,inplace=True)
df['M2'].replace(np.nan,mas_freqM1,inplace=True)
df['M3'].replace(np.nan,mas_freqM1,inplace=True)
df['M4'].replace(np.nan,mas_freqM1,inplace=True)
df['M5'].replace(np.nan,mas_freqM1,inplace=True)
df['M6'].replace(np.nan,mas_freqM1,inplace=True)

La variable mas frecuente para M1 es -1.0
La variable mas frecuente para M2 es -1.0
La variable mas frecuente para M3 es -1.0
La variable mas frecuente para M4 es -1.0
La variable mas frecuente para M5 es -1.0
La variable mas frecuente para M6 es -1.0


C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\68965767.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['M1'].replace(0,np.nan,inplace=True)
C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\68965767.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when do

In [21]:
dfM1=df['M1'].unique()
dfM2=df['M2'].unique()
dfM3=df['M3'].unique()
dfM4=df['M4'].unique()
dfM5=df['M5'].unique()
dfM6=df['M6'].unique()
print(f'M1{dfM1}')
print(f'M2{dfM2}')
print(f'M3{dfM3}')
print(f'M4{dfM4}')
print(f'M5{dfM5}')
print(f'M6{dfM6}')

M1[ 2. -1.  1.  3.  4.  8.  7.  5.  6.]
M2[ 2. -1.  3.  5.  7.  4.  1.  6.  8.]
M3[-1.  2.  3.  4.  6.  7.  1.  5.  8.]
M4[-1.  2.  3.  4.  5.  7.  6.  1.  8.]
M5[-1.  2.  3.  5.  4.  7.  8.  6.]
M6[-1.  2.  3.  6.  4.  7.  8.  5.]


In [22]:
df.count()

ID    30000
CU    30000
G     30000
ED    30000
EC    30000
E     30000
M1    30000
M2    30000
M3    30000
M4    30000
M5    30000
M6    30000
D1    30000
D2    30000
D3    30000
D4    30000
D5    30000
D6    30000
P1    30000
P2    30000
P3    30000
P4    30000
P5    30000
P6    30000
SP    30000
dtype: int64

In [23]:
df.describe()

ID             CU            ED             E            M1  \
count  30000.000000   30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   16748.432267      1.819267     35.485500     -0.415967   
std     8660.398374   12974.766157      0.707450      9.217904      1.142591   
min        1.000000    1000.000000      1.000000     21.000000     -1.000000   
25%     7500.750000    5000.000000      1.000000     28.000000     -1.000000   
50%    15000.500000   14000.000000      2.000000     34.000000     -1.000000   
75%    22500.250000   24000.000000      2.000000     41.000000     -1.000000   
max    30000.000000  100000.000000      4.000000     79.000000      8.000000   

                 M2            M3            M4            M5            M6  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      -0.532033     -0.555500     -0.624233     -0.679567     -0.670800   
std        1.146393      1.126275      1.067522      1.001726      1.005283   
min       -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
25%       -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
75%       -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
max        8.000000      8.000000      8.000000      8.000000      8.000000   

       ...             D3            D4            D5            D6  \
count  ...   30000.000000  30000.000000  30000.000000  30000.000000   
mean   ...    4701.315480   4326.294897   4031.140097   3887.176040   
std    ...    6934.938743   6433.285613   6079.715577   5955.410754   
min    ...  -15726.400000 -17000.000000  -8133.400000 -33960.300000   
25%    ...     266.625000    232.675000    176.300000    125.600000   
50%    ...    2008.850000   1905.200000   1810.450000   1707.100000   
75%    ...    6016.475000   5450.600000   5019.050000   4919.825000   
max    ...  166408.900000  89158.600000  92717.100000  96166.400000   

                 P1            P2            P3            P4            P5  \
count  30000.000000   30000.00000  30000.000000  30000.000000  30000.000000   
mean     566.358050     592.11635    522.568150    482.607687    479.938763   
std     1656.328035    2304.08704   1760.696147   1566.615974   1527.830568   
min        0.000000       0.00000      0.000000      0.000000      0.000000   
25%      100.000000      83.30000     39.000000     29.600000     25.250000   
50%      210.000000     200.90000    180.000000    150.000000    150.000000   
75%      500.600000     500.00000    450.500000    401.325000    403.150000   
max    87355.200000  168425.90000  89604.000000  62100.000000  42652.900000   

                 P6  
count  30000.000000  
mean     521.550257  
std     1777.746578  
min        0.000000  
25%       11.775000  
50%      150.000000  
75%      400.000000  
max    52866.600000  

[8 rows x 22 columns]

In [24]:
df.head()

ID     CU  G  ED       EC   E   M1   M2   M3   M4  ...      D4      D5  \
0   1   2000  F   2   Casado  24  2.0  2.0 -1.0 -1.0  ...     0.0     0.0   
1   2  12000  F   2  Soltero  26 -1.0  2.0 -1.0 -1.0  ...   327.2   345.5   
2   3   9000  F   2  Soltero  34 -1.0 -1.0 -1.0 -1.0  ...  1433.1  1494.8   
3   4   5000  F   2   Casado  37 -1.0 -1.0 -1.0 -1.0  ...  2831.4  2895.9   
4   5   5000  M   2   Casado  57 -1.0 -1.0 -1.0 -1.0  ...  2094.0  1914.6   

       D6     P1      P2      P3     P4     P5     P6  SP  
0     0.0    0.0    68.9     0.0    0.0    0.0    0.0  Si  
1   326.1    0.0   100.0   100.0  100.0    0.0  200.0  Si  
2  1554.9  151.8   150.0   100.0  100.0  100.0  500.0  No  
3  2954.7  200.0   201.9   120.0  110.0  106.9  100.0  No  
4  1913.1  200.0  3668.1  1000.0  900.0   68.9   67.9  No  

[5 rows x 25 columns]

### Cambio de variables de las columnas G, EC, SP

In [25]:
df['G'].unique()

array(['F', 'M', 'O'], dtype=object)

In [26]:
# Cambiar F=0, M=1, O=2
df['G'].replace('F',0,inplace=True)
df['G'].replace('M',1,inplace=True)
df['G'].replace('O',2,inplace=True)
df['G'].unique()

C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\4189437334.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['G'].replace('F',0,inplace=True)
C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\4189437334.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when do

array([0, 1, 2], dtype=int64)

In [27]:
df['EC'].unique()

array(['Casado', 'Soltero', 'Otros'], dtype=object)

In [28]:
df['EC'].replace('Casado',0,inplace=True)
df['EC'].replace('Soltero',1,inplace=True)
df['EC'].replace('Otros',2,inplace=True)
df['EC'].unique()

C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\334729365.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['EC'].replace('Casado',0,inplace=True)
C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\334729365.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, whe

array([0, 1, 2], dtype=int64)

In [29]:
df['SP'].unique()

array(['Si', 'No'], dtype=object)

In [30]:
df['SP'].replace('Si',0,inplace=True)
df['SP'].replace('No',1,inplace=True)
df['SP'].unique()

C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\3976390147.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SP'].replace('Si',0,inplace=True)
C:\Users\cesar\AppData\Local\Temp\ipykernel_13620\3976390147.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when 

array([0, 1], dtype=int64)

In [31]:
df.head(10)

ID     CU  G  ED  EC   E   M1   M2   M3   M4  ...       D4       D5  \
0   1   2000  0   2   0  24  2.0  2.0 -1.0 -1.0  ...      0.0      0.0   
1   2  12000  0   2   1  26 -1.0  2.0 -1.0 -1.0  ...    327.2    345.5   
2   3   9000  0   2   1  34 -1.0 -1.0 -1.0 -1.0  ...   1433.1   1494.8   
3   4   5000  0   2   0  37 -1.0 -1.0 -1.0 -1.0  ...   2831.4   2895.9   
4   5   5000  1   2   0  57 -1.0 -1.0 -1.0 -1.0  ...   2094.0   1914.6   
5   6   5000  1   1   1  37 -1.0 -1.0 -1.0 -1.0  ...   1939.4   1961.9   
6   7  50000  1   1   1  29 -1.0 -1.0 -1.0 -1.0  ...  54265.3  48300.3   
7   8  10000  0   2   1  23 -1.0 -1.0 -1.0 -1.0  ...     22.1    -15.9   
8   9  14000  0   3   0  28 -1.0 -1.0  2.0 -1.0  ...   1221.1   1179.3   
9  10   2000  1   3   1  35 -1.0 -1.0 -1.0 -1.0  ...      0.0   1300.7   

        D6      P1      P2      P3      P4      P5      P6  SP  
0      0.0     0.0    68.9     0.0     0.0     0.0     0.0   0  
1    326.1     0.0   100.0   100.0   100.0     0.0   200.0   0  
2   1554.9   151.8   150.0   100.0   100.0   100.0   500.0   1  
3   2954.7   200.0   201.9   120.0   110.0   106.9   100.0   1  
4   1913.1   200.0  3668.1  1000.0   900.0    68.9    67.9   1  
5   2002.4   250.0   181.5    65.7   100.0   100.0    80.0   1  
6  47394.4  5500.0  4000.0  3800.0  2023.9  1375.0  1377.0   1  
7     56.7    38.0    60.1     0.0    58.1   168.7   154.2   1  
8    371.9   332.9     0.0    43.2   100.0   100.0   100.0   1  
9   1391.2     0.0     0.0     0.0  1300.7   112.2     0.0   1  

[10 rows x 25 columns]

# Entrenamiento de los datos

In [32]:
# Matriz X de entrada
X = df.drop(["SP",'ID'], axis=1)
#X=df.drop('ID',axis=1)
# vector y de salida
Y = df["SP"]

X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=20) 

#### Comprobacion de las matrices

In [33]:
X.head(10)

CU  G  ED  EC   E   M1   M2   M3   M4   M5  ...       D3       D4  \
0   2000  0   2   0  24  2.0  2.0 -1.0 -1.0 -1.0  ...     68.9      0.0   
1  12000  0   2   1  26 -1.0  2.0 -1.0 -1.0 -1.0  ...    268.2    327.2   
2   9000  0   2   1  34 -1.0 -1.0 -1.0 -1.0 -1.0  ...   1355.9   1433.1   
3   5000  0   2   0  37 -1.0 -1.0 -1.0 -1.0 -1.0  ...   4929.1   2831.4   
4   5000  1   2   0  57 -1.0 -1.0 -1.0 -1.0 -1.0  ...   3583.5   2094.0   
5   5000  1   1   1  37 -1.0 -1.0 -1.0 -1.0 -1.0  ...   5760.8   1939.4   
6  50000  1   1   1  29 -1.0 -1.0 -1.0 -1.0 -1.0  ...  44500.7  54265.3   
7  10000  0   2   1  23 -1.0 -1.0 -1.0 -1.0 -1.0  ...     60.1     22.1   
8  14000  0   3   0  28 -1.0 -1.0  2.0 -1.0 -1.0  ...   1210.8   1221.1   
9   2000  1   3   1  35 -1.0 -1.0 -1.0 -1.0 -1.0  ...      0.0      0.0   

        D5       D6      P1      P2      P3      P4      P5      P6  
0      0.0      0.0     0.0    68.9     0.0     0.0     0.0     0.0  
1    345.5    326.1     0.0   100.0   100.0   100.0     0.0   200.0  
2   1494.8   1554.9   151.8   150.0   100.0   100.0   100.0   500.0  
3   2895.9   2954.7   200.0   201.9   120.0   110.0   106.9   100.0  
4   1914.6   1913.1   200.0  3668.1  1000.0   900.0    68.9    67.9  
5   1961.9   2002.4   250.0   181.5    65.7   100.0   100.0    80.0  
6  48300.3  47394.4  5500.0  4000.0  3800.0  2023.9  1375.0  1377.0  
7    -15.9     56.7    38.0    60.1     0.0    58.1   168.7   154.2  
8   1179.3    371.9   332.9     0.0    43.2   100.0   100.0   100.0  
9   1300.7   1391.2     0.0     0.0     0.0  1300.7   112.2     0.0  

[10 rows x 23 columns]

In [34]:
Y.head(10)

0    0
1    0
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: SP, dtype: int64

### Entrenamiento

In [35]:
# Importar modelo random forest. 
rf = RandomForestClassifier(n_estimators=50, random_state=42)
#entrenar modelo 
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=42)

In [36]:
y_pred = rf.predict(X_test) # variable predichas por el modleo

exactitud = accuracy_score(y_test, y_pred)

print(f"El modelo de Random Forest obtuvo una exactitud de: {exactitud}")

El modelo de Random Forest obtuvo una exactitud de: 0.8146666666666667


### Matriz de confucion

In [37]:
# Matriz de confusion
con_mat=confusion_matrix(y_test,y_pred)
print(f'Matriz de confusion:\n{con_mat}')
#exactitud
exactitud=accuracy_score(y_test,y_pred)
#precision
precision=precision_score(y_test,y_pred)
#sensibilidad
recall=recall_score(y_test,y_pred)

#Especificidad

vn,fp,fn,vp=con_mat.ravel()
especificidad=vn/(vn+fp)
#f1-score
f1=f1_score(y_test,y_pred)

print(f'Exactitud: {exactitud: .2f}\nPresicion:{precision: .2f}\nSensibilidad: {recall: .2f}\nEspecificidad{especificidad: .2f}\nf1-score: {f1: .2f}')

Matriz de confusion:
[[ 785 1212]
 [ 456 6547]]
Exactitud:  0.81
Presicion: 0.84
Sensibilidad:  0.93
Especificidad 0.39
f1-score:  0.89


###### El proceso es capas de identificar de mejor manera los casos positivos pero no logra predecir bien los casos negativos

In [38]:
# EVALUACION DEL MODELO
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.63      0.39      0.48      1997
           1       0.84      0.93      0.89      7003

    accuracy                           0.81      9000
   macro avg       0.74      0.66      0.69      9000
weighted avg       0.80      0.81      0.80      9000



#### Boosting

In [39]:
from xgboost import XGBClassifier
xgb = XGBClassifier(use_label_encoder=False)

#entrenamiento 
xgb.fit(X_train, y_train)
#Prediccion 
y_pred = xgb.predict(X_test)
#Validacion
print(classification_report(y_test, y_pred))
print("Matriz de confusion: ")
print(confusion_matrix(y_test, y_pred))

c:\Users\cesar\anaconda3\envs\endomorfismo\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")


              precision    recall  f1-score   support

           0       0.63      0.38      0.47      1997
           1       0.84      0.94      0.89      7003

    accuracy                           0.81      9000
   macro avg       0.74      0.66      0.68      9000
weighted avg       0.79      0.81      0.79      9000

Matriz de confusion: 
[[ 750 1247]
 [ 440 6563]]


### Mejor modelo entrenado Pickle

In [40]:
import pickle


filename= 'Mejor_Modelo_Pickle.sav'
pickle.dump(rf, open(filename, 'wb'))

In [41]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)

print(f'la exactitud es:\n{result}')

la exactitud es:
0.8146666666666667


### Mejor Modelo entrenado joblib

In [42]:
import joblib
filename = 'Mejor_Modelo_joblib.sav'
joblib.dump(rf, filename)

['Mejor_Modelo_joblib.sav']

In [43]:
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(f'la exactitud es:\n{result}')

la exactitud es:
0.8146666666666667
